#docker compose -f compose.dev.yaml up -d --force-recreate
#the force recreate is just in case you're tweaking things on the .env
services:
  mamapidev:
    build:
      context: .
    container_name: mamapidev
    volumes:
      - ../instance/data:/data
      - ../mamapi.py:/usr/src/app/mamapi.py:ro
    environment:
      - MAM_ID=${MAM_ID}
      - DEBUG=${DEBUG}
      - TZ=${TZ}
    network_mode: "container:gluetun"